version: "3.8"
services:
  backend:
    image: backend:latest
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - /home/work/devops-mlops/mlops/backend-volume:/app/backend
    networks:
      - my-network
    depends_on:
      - db
    environment:
      - POSTGRES_USER: ${{ secrets.DB_USER_DEV }}
      - POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
      - POSTGRES_DB: ${{ vars.DB_DBNAME_DEV }}
      - POSTGRES_HOST: ${{ secrets.DB_HOST_DEV }}
      - POSTGRES_PORT: ${{ secrets.DB_PORT_DEV }}

  db:
    image: postgres:latest
    container_name: db-container
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-volume:
