version: "3.8"
services:
  app-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 5002:5000
    env_file:
      - .env
    networks:
      - my-network
      
  backend:
    image: backend:latest
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: db-container
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-volume:
