version: "3.8"
services:
  app-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 5002:5000
    env_file:
      - .env
    networks:
      - my-network

  db:  
    container_name: postgres-container
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  pgdata:
